### ISSUE TITLE
Conflict between plink for GWAS and plink the networking tool on Linux

### ISSUE THREAD

**Issue by esohkevin** [h3abionet/h3agwas#13]
Dear Prof Scott

Thank you for making GWAS so simple with this h3agwas pipeline. I am using the pipeline in parallel with local gwas tools like Plink, QCTOOL, IMPUTE2 etc to compare my results.

I just recently installed the pipeline on my account on the DELGEME bio server since it requires no root privileges and will run faster there.

However, it spilt some errors (below) when I tried running the tutorial.

```nextflow run plink-qc.nf --input_pat sampleA --input_dir sample```

N E X T F L O W  ~  version 18.10.1
Launching `plink-qc.nf` [cranky_perlman] - revision: f986962b17
Sexinfo available command
[warm up] executor > local
[8a/01c9f4] Submitted process > inMD5 (1)
[40/3c2c85] Submitted process > getDuplicateMarkers (1)
[58/52ead8] Submitted process > removeDuplicateSNPs (1)
ERROR ~ Error executing process > 'removeDuplicateSNPs (1)'

Caused by:
  Process `removeDuplicateSNPs (1)` terminated with an error exit status (1)

Command executed:

  **plink** --keep-allele-order --bfile sampleA  --must-have-sex --exclude sampleA.dups --missing --make-bed --out sampleA-nd
  wc -l sampleA.bim > sampleA.orig
  wc -l sampleA.fam >> sampleA.orig

Command exit status:
  1

Command output:
  (empty)

Command error:
  **plink: unknown option "--keep-allele-order"
  plink: unknown option "--bfile"
  plink: unknown option "--must-have-sex"
  plink: unknown option "--exclude"**

I observed the ```plink-qc.nf``` file and noticed that plink is written simply as ```plink``` which is the same as the connectivity tool
```
Plink: command-line connection utility
Release 0.67
Usage: plink [options] [user@]host [command]
       ("host" can also be a PuTTY saved session name)
```
I am not sure how significant the error is but I just thought it is worth pointing out since some users managing the pipeline with Git might potentially encounter this.

We have plink on the server, but the executable file was renamed to plink1 in order to prevent the conflict. We also have plink1.9 which is actually named as ```plink1.9```

One fix for the conflict that I thought of doing was to manually edit the pink in all the executables to plink1.9.

However, is there a possibility to add _program_ as a parameter in the _.config_ file so that users can specify what version they want to use, and then call it up in the _.nf_ and _.sh_ executables as a variable? This may potentially be useful in making the pipeline support plink2 which you raised as an issue, and other versions.

Please pardon the typos, I am just a novice :)

Thanks,
Esoh

**Comment by shaze** [comment]
Dear Esoh

Thank you for your comments.  Yes, I am aware of this potential conflict. 

There is a tension between making the worflow more generalisable and harder to use. Adding extra options to support thise case makes the pipeline more difficult for others to use (since it's not just plink  that could possibly be named this way) and since there are alternatives I'd prefer not to do it.

Does anyone in your group actually use the other plink (the connectivity tool)?  My experience is that `ssh` would more likely to be used. My suggestion would be to see if you could remove it.

However, if you can't do this system wide, you can set up your own environment by doing a sym link to an appropriate place in your own directory and then setting up your environment

e.g. something line 
```
ln -s /usr/bin/plink1.6 /home/esoh/lib/plink
``` 
and then add to your `.bashrc` file

```
export PATH=/home/esoh/lib/plink:${PATH}
```

**Comment by esohkevin** [comment]
Dear Prof Scott,

Many thanks for your quick response. 
These should absolutely solve the conflict.
