### ISSUE TITLE
Not possible to copy ami-9ca7b2fa AWS AMI storage snapshot 

### ISSUE THREAD

**Issue by getconor** [h3abionet/h3agwas#2]
When using AWS it is possible to launch the ami-9ca7b2fa AMI, but any attempts to copy produce the error message: "You do not have permission to access the storage of this ami".

I suspect that although the AMI itself is public, the underlying snapshot is not public, preventing copying and preventing the ability to copy the snapshot to:  1) a different region and, 2) an encrypted snapshot in order to enable root volume encryption.

Could this be enabled, or is there a reason that the underlying storage should not be publicly accessible?

**Comment by shaze** [comment]
Dear Conor. Thank you for reporting this and apologies for the delay. I was on leave and then I wanted to wait for an update to the workflow to finish. We've had to release a new AMI because Nextflow now wants Java 8. The new AMI is ami-710b9108. I have made the snapshot and image public.

Many thanks

**Comment by getconor** [comment]
No worries! I look forward to trying out the new AMI.

**Comment by getconor** [comment]
Copied successfully. Thanks!
