### ISSUE TITLE
qc.nf fails during getDuplicateMarkers due to chr prefix / non-autosomal chrs

### ISSUE THREAD

**Issue by PhilPalmer** [h3abionet/h3agwas#24]
Hi,

I am trying to run the `qc.nf` script. It works with the `sample` data, however, when I try & run it with my own data it fails during the `getDuplicateMarkers` process (see [nextflow.log](https://github.com/h3abionet/h3agwas/files/3627781/nextflow.log))

I think the problem comes from this [line](https://github.com/h3abionet/h3agwas/blob/master/templates/dups.py#L38) in `dups.py` as the error message is (edited for brevity):
```
Caused by:
  Process `getDuplicateMarkers (1)` terminated with an error exit status (1)

..........

Command error:
  Traceback (most recent call last):
    File ".command.sh", line 71, in <module>
      removeOnBP(sys.argv[1],out)
    File ".command.sh", line 43, in removeOnBP
      elif (chrom, bp) > (old_chrom, old_bp):
  TypeError: '>' not supported between instances of 'str' and 'int'
``` 

I have tried printing the value of the chrs that cause a problem (see [print_chr_nextflow.log](https://github.com/h3abionet/h3agwas/files/3627777/print_chr_nextflow.log)) & it seems to be due to the chromosome being `chr1` (it also fails with chr `X`). The problem occurs because this is not an `int` and python cannot make the comparison.

Any ideas on the best way to fix this? 

(It's also worth noting that I am running my fork of the pipeline which I have made changes to but I think this is also a problem for this pipeline)

Many thanks in advance,
Phil

**Comment by shaze** [comment]
Phil
We look at and see how to fix.

As a matter of interest, how are you producing the input PLINK file -- it's not typical that the "chr" survives, and usually PLINK encodes chromosomes 24, 25, 26 rather than X, Y...

A quick fix for you would be to run your data through plink once 

`plink --bfile input --make-bed --out output`

PLINK will then autoconvert all the chr encodings

I'd like our scripts to be robust so will fix but this might work for you in the meantime

**Comment by PhilPalmer** [comment]
Ah sorry, I didn't realise that PLINK files do not typically have the `chr` prefix

I am making the plink files from VCF eg `plink --vcf $vcf`. I have just ran your command now and that solves it

Thank you very much for your help & prompt response

**Comment by shaze** [comment]
Thanks Phil. Having looked at it, I think the best is to require that the PLINK file is in the canonical PLINK format. I think there are other dependencies too. I'll change the script so that it dies gracefully with a useful error message. I could put the automatic PLINK conversion in, but this might hide some other problem.  

Thanks -- this has been very useful

**Comment by shaze** [comment]
Phil -- I have pushed through a change that checks the problem and prints a proper error message. We discussed it internally and will look at doing at handling the problem but we don't want to do a quick fix internally

**Comment by PhilPalmer** [comment]
Okay, that's great. Thank you very much @shaze 

Just printing a proper error message works well for me

**Comment by shaze** [comment]
Hope all OK
